### PR TITLE
Disable Tango interface

### LINKED ISSUE #179: Running in nodb mode without Tango environment produces an error in org.tango.client.database.Database
```
ERROR 2019-01-25 15:19:37,515 [http-nio-10001-exec-4 -  - o.t.c.d.Database] org.tango.client.database.Database.<init>:46 - error loading db cache, exception message is: IDL:Tango/DevFailed:1.0
Error Level 0:
         - desc: Unknown "TANGO_HOST" property 
         - origin: TangoUrl.setFromEnv()
         - reason: TangoApi_TANGO_HOST_NOT_SET
         - severity: PANIC
```

### PR DESCRIPTION
**Pull request by Ingvord**
Rest server should not include Tango Server

Motivation:

1. migration to pure microservices
2. reduce dependencies
3. decrease application footprint

Resolves #179

### CODE REVIEW

File: src/test-integration/java/org/tango/rest/TangoRestServer.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+        Path baseDir = Paths.get("target/webapp");
+
+        Tomcat tomcat = new TomcatBootstrap(10001, baseDir,
+                new AuthConfiguration("plain", new String[]{"tango-cs"}, new String[]{"tango"}),
+                new WebappConfiguration(baseDir.toAbsolutePath().toString()),
+                new AccessLogConfiguration(),
+                new Http2Configuration("/etc/ssl/certs/ssl-cert-snakeoil.pem", "/etc/ssl/private/ssl-cert-snakeoil.key"))
+                .bootstrap();
+
+        tomcat.getServer().await();
```
Comment (Ingvord) [inline src/test-integration/java/org/tango/rest/TangoRestServer.java:24]: https://devcenter.heroku.com/articles/create-a-java-web-application-using-embedded-tomcat
